### ISSUE TITLE
 Larger Image for First Application

### ISSUE THREAD

**Issue by jjbstudent** [jjbstudent/Responsive-Profile#5]
# Issue: Larger Image for First Application

## Description
When presented with your first application in the work section, that application's image should be larger in size than the others.

## Tasks
- [x] Identify the first application in your work section.
- [x] Adjust the size of the image for the first application to be larger than the others.
- [x] Test the layout to confirm that the first application's image is appropriately sized.
